#!/usr/bin/env bash
#
# Script to perform a Jekyll deploy for thebestmotherfuckingwebsite.co
#

JEKYLL_DEST=/var/www/thebestmotherfuckingwebsite.co/public_html
WWW_ROOT=/var/www

echo -e "Building Jekyll site to ${JEKYLL_DEST}..."
bundle exec jekyll build -d $JEKYLL_DEST

# Test if jekyll build was succesfull
RESULT_JEKYLL=$?
if [ $RESULT_JEKYLL -ne 0 ]; then
  # Exit if build failed
  echo -e "\nDeployment failed: Jekyll build failed."
  exit 1
fi

# Remove CNAME
echo -e "\nRemoving CNAME..."
rm ${JEKYLL_DEST}/CNAME

echo -e "\nJekyll build successful."
exit

